print("cuanto pagas de local")
pago_local = int(input() )
print ("cual es el total de pago por empleado")
pago_empleado = int(input() )
print("cuanto gastas de mercancia en un mes aproximadamente")
pago_mercancia = int(input() )
print("cuanto generas en un mes aproximadamente")
ganancias = int(input() )

ganancias1 = print(ganancias - pago_local)
ganancias2 = print(ganancias1 - pago_empleado)
ganancias3 = print(ganancias2 - pago_mercancia)

print(ganacias3 * 6)
print("esta es tu ganancia en 6 meses")
