print("marielisa \n")

print("digite su nombre")
nombre = input()
print("digite su edad")
edad = int(input())
print("digita un numero de tu preferencia del 1 al 4")
numero1 = int(input() )
print("digita otro numero de tu preferencia del 1 al 4")
numero2 = int(input())

# aqui vemos como usamos los print e input donde correpondes para la correcta ejecucion del programa.

suma = (numero1 + numero2)
resta = (numero1 - numero2)
multiplicacion = (numero1 * numero2)
division = (numero1 / numero2)


